outbreak-info/outbreak.info

web/src/App.vue
web/src/router/index.js

active class fixed; weird CSS transition needs fixing?

partial fix of nav active state

---

web/src/App.vue
web/src/api/epi-basics.js
web/src/api/epi-geo.js
web/src/components/Bargraph.vue
web/src/components/DataSource.vue
web/src/components/DoublingTable.vue
web/src/components/EpiCurve.vue
web/src/components/EpiStacked.vue
web/src/components/EpiTable.vue
web/src/components/LeafletMap.vue
web/src/router/index.js
web/src/store/modules/admin.js
web/src/views/About.vue
web/src/views/Data.vue
web/src/views/DoublingRates.vue
web/src/views/Epi.vue
web/src/views/Sources.vue

- Change U.S. data source to NYT
- Add metro area aggregations
- Add /source
- Adjust plots for higher case counts :(

Switch data to NYT, add metro areas

---

web/src/api/biothings.js
web/src/api/calc-doubling.js
web/src/api/epi-basics.js
web/src/api/epi-geo.js
web/src/api/epi-traces.js
web/src/api/region-summary.js
web/src/components/Bargraph.vue
web/src/components/CaseSummary.vue
web/src/components/CountryBarGraph.vue
web/src/components/EpiCurve.vue
web/src/components/EpiStacked.vue
web/src/components/EpiTable.vue
web/src/components/GlanceSummary.vue
web/src/components/LeafletMap.vue
web/src/components/RecoveredBar.vue
web/src/router/index.js
web/src/store/modules/admin.js
web/src/styles/_variables.scss
web/src/views/Data.vue
web/src/views/Epi.vue
web/src/views/Home.vue
web/src/views/Latest.vue

Also changes from `_currentCases` to `mostRecent` architecture of API (#53) (fixes #67).
closes #42 from the front-end side

Normalize x-axis by days since 100 cases, 10 deaths, or 50 deaths

---

web/src/api/resources.js

allow multiselect of properties, update counts on filter

---

web/src/App.vue
web/src/api/epi-comparison.js
web/src/components/Choropleth.vue
web/src/components/HistogramLegend.vue
web/src/store/modules/admin.js
web/src/views/Compare.vue

In response to #134 -- partial fix.

Improved choropleth behavior

---

web/src/components/EpiCurve.vue
web/src/router/index.js
web/src/store/modules/admin.js
web/src/views/Epi.vue

Add rolling average direct comparison

---

web/src/api/epi-traces.js
web/src/components/Bargraph.vue
web/src/components/EpiCurve.vue
web/src/js/get_svg.js
web/src/router/index.js
web/src/store/modules/admin.js
web/src/views/Compare.vue
web/src/views/Epi.vue

Add in per capita calcs to maps, epi

---

web/src/components/ReportMethodology.vue
web/src/views/SituationReportsCaveats.vue

added text to the methodology and caveats pages for Mutation Situation Reports

closes #220, closes #217

---

web/src/components/ReportChoropleth.vue
web/src/components/ReportPrevalence.vue
web/src/components/ReportPrevalenceByLocation.vue
web/src/components/ReportSummary.vue
web/src/components/ShareReport.vue
web/src/components/Warning.vue
web/src/views/SituationReport.vue

Improved mobile display

---

web/src/api/genomics.js
web/src/components/CharacteristicMutations.vue
web/src/components/CustomLocationForm.vue
web/src/components/LineagesByLocation.vue
web/src/components/MutationHeatmap.vue
web/src/components/OverlayLineagePrevalence.vue
web/src/components/ReportChoropleth.vue
web/src/components/ReportPrevalenceOverlay.vue
web/src/components/ReportStackedBarGraph.vue
web/src/components/SARSMutationMap.vue
web/src/components/SequencingHistogram.vue
web/src/router/index.js
web/src/views/LocationReport.vue
web/src/views/SituationReport.vue

- Improved sequence count histogram behavior
- add imperfect copy/download
- updated spacing / layout
- add checks for no data
- add "other" lineages def
- add epi/mutation overlay zoom as url param
- add scale / legend to char muts per location
- fix window change --> no data
- add definition of char muts
- deduplicated mutations on top of lineages

Location report cleanup

---

web/src/assets/genomics/curated_lineages.json
web/src/store/modules/admin.js

Waiting on Pangolin update to add AY.2 as a VOC

2021 06 18 classification updates

---

web/src/assets/genomics/curated_lineages.json
web/src/store/modules/admin.js

Waiting for Pangolin update to reclassify B.1.617.2 sequences as AY.2. Derivative of PR #381

2021 06 18 ay.2 addition

---

web/src/components/GradientLegend.vue
web/src/components/MutationHeatmap.vue
web/src/components/ReportMethodology.vue
web/src/router/index.js
web/src/store/modules/admin.js
web/src/styles/_objects.scss
web/src/views/LocationReport.vue
web/src/views/SituationReportComparison.vue
web/src/views/SituationReports.vue

- Add light/dark mode closes #376 
- Add warning for a low number of sequences

Mut heatmap revision

---

web/src/views/LocationReport.vue

connect recent window form to changing the "other" category in the stream graph

link recent window --> day threshold value

---

web/src/api/genomics.js
web/src/components/GradientLegend.vue
web/src/components/ReportChoropleth.vue
web/src/components/ReportPrevalenceByLocation.vue
web/src/store/modules/admin.js
web/src/views/LocationReport.vue
web/src/views/SituationReport.vue

Also allow clicking on map --> navigate to report

Link Variant reports --> location reports

---

web/src/views/SituationReport.vue

Fixed type from *lingeage* to *lineage* on the situation report view.

Update SituationReport.vue for Typo

---

web/src/components/LineageComparisonComponent.vue
web/src/components/LineagesByLocation.vue
web/src/components/LocationReportComponent.vue
web/src/components/LocationTable.vue
web/src/components/MutationHeatmap.vue
web/src/components/ReportPrevalenceOverlay.vue
web/src/components/ReportStackedBarGraph.vue
web/src/components/ReportSummary.vue
web/src/components/SituationReportComponent.vue
web/src/views/GenomicsEmbed.vue

1. location reports: stacked bar chart (last 60 days)
2. mutation heatmap: lineage/mutation click
3. location reports: prevalence over time click on variant name
4. location reports: table of VOCs

Fixed embed routing

---

web/src/views/Press.vue

update: break press articles by year

---

web/src/components/SituationReportComponent.vue
web/src/views/SituationReport.vue

fix: mutation of prop selected error

---

web/src/components/ReportPrevalence.vue
web/src/components/ReportPrevalenceOverlay.vue

fix: ticks in small screens

---

web/src/api/epi-traces.js
web/src/components/Bargraph.vue
web/src/components/LineagesByLocation.vue
web/src/components/LocationReportComponent.vue
web/src/components/LocationTable.vue
web/src/components/ReportPrevalence.vue
web/src/components/ReportPrevalenceOverlay.vue
web/src/components/SublineageTotals.vue
web/src/components/TypeaheadSelect.vue
web/src/js/get-date.js
web/src/styles/_basics.scss
web/src/views/LocationReport.vue
web/src/views/Regions.vue

- 2-vis-cleanup tasks
#561, #562, #567, #571, #572, #573

update: 2-vis-cleanup tasks

---

web/src/components/LineagesByLocation.vue

chore: add suggest note for only other data case

---

web/src/components/ReportPrevalence.vue

fix: large rect error

---

web/src/components/LineagesByLocation.vue
web/src/components/ReportPrevalence.vue
web/src/components/ReportPrevalenceOverlay.vue

- wrong css issue in date range buttons due to not syncing param

fix: wrong css due to not sync params issue

---

web/src/components/ReportAcknowledgements.vue
web/src/views/Citation.vue
web/src/views/Faq.vue
web/src/views/Privacy.vue
web/src/views/Schema.vue
web/src/views/Terms.vue

- horizontal scroll issue in citation, faq, schema, terms, privacy policy pages

fix: horizontal scroll issue

---

web/src/components/LineageComparisonComponent.vue

Fix: Limited visualization by browser window width

---

web/src/components/LineageComparisonComponent.vue

fix: Insertions caveat inconsistently displayed

---

web/src/api/genomics.js

chore: add size param

---

web/src/components/MutationsByLineage.vue

update: Only show the top 10 lineages for a mutation report page #631

---

web/src/api/genomics.js
web/src/components/LineageComparisonComponent.vue

Update: Change gene filteration on CompareLineageComponent to rely on API calls #629

---

web/src/views/GrowthRatesPage.vue

This PR adds meta tags to the growth rates page. Please refer to PR #676 for further information.

feat: add metadata to growth rates page

---

web/src/api/growth-rates.js
web/src/api/lineage-and-location-names.js
web/src/api/significance.js
web/src/components/GrForm.vue
web/src/components/GrIntro.vue
web/src/components/GrSuggestedLineages.vue
web/src/components/GrTooltip.vue
web/src/components/GrVisInfo.vue
web/src/components/GrVisualizations.vue
web/src/components/GrWarning.vue
web/src/views/GrowthRatesPage.vue

This PR implements the following features:
- aggregated lineage selection
- global selection
- high-growth lineages in the world presented as suggestions

Fix/no ref/handle leaf field

---

web/src/views/About.vue
web/src/views/Home.vue

This PR prevents the `Jobs` component from being rendered.

fix: remove job ads

---

web/src/api/genomics.js

The [API handlers](https://github.com/outbreak-info/outbreak.api/pull/96) have been modified to improve performance. This PR ensures that the outbreak.info UI will work flawlessly after said modifications.

Feature/no ref/api v3

---

web/src/components/GrTooltip.vue

This PR fixes the information displayed by tooltips from the growth rates page.

fix: correct info presented by tooltips

---

web/src/App.vue

This PR updates the notices section and adds header and footer links to wastewater surveillance visualizations.

Header and footer updates

---

web/src/App.vue

This PR updates the links to the wastewater app to reflect route changes.

feat: update links to wastewater app

---

web/src/App.vue

This PR adds links to the wastewater lineage tracker view.

feat: update header and footer
